# Generated by Django 5.2.3 on 2025-07-09 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
            ],
            options={
                'permissions': [('advanced', 'Advanced Permission'), ('pro', 'Pro Permission'), ('basic', 'basic permission')],
            },
        ),
    ]
