# Generated by Django 5.2.4 on 2025-07-13 06:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('active', models.BooleanField(default=True)),
                ('stripe_id', models.CharField(blank=True, max_length=150, null=True)),
                ('order', models.IntegerField(default=-1, help_text='Ordering on Django pricing page')),
                ('featured', models.BooleanField(default=True, help_text='Featured on Django pricing page')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(to='auth.group')),
                ('permissions', models.ManyToManyField(limit_choices_to={'codename__in': ['advanced', 'pro', 'basic'], 'content_type__app_label': 'subscriptions'}, to='auth.permission')),
            ],
            options={
                'ordering': ['order', 'featured', '-updated'],
                'permissions': [('advanced', 'Advanced Permission'), ('pro', 'Pro Permission'), ('basic', 'Basic Permission')],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_id', models.CharField(blank=True, max_length=150, null=True)),
                ('interval', models.CharField(choices=[('month', 'MONTHLY'), ('year', 'Year')], default='month', max_length=120)),
                ('price', models.DecimalField(decimal_places=2, default=99.99, max_digits=10)),
                ('order', models.IntegerField(default=-1, help_text='Ordering on Django pricing page')),
                ('featured', models.BooleanField(default=True, help_text='Featured on Django pricing page')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='subscriptions.subscription')),
            ],
            options={
                'ordering': ['order', 'featured', '-updated'],
            },
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='Date Of subscription')),
                ('active', models.BooleanField(default=True)),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='subscriptions.subscription')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
