# Generated by Django 5.2.3 on 2025-07-09 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('subscriptions', '0002_subscription_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='permission',
            field=models.ManyToManyField(to='auth.permission'),
        ),
    ]
