# Generated by Django 5.2.3 on 2025-07-09 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('subscriptions', '0003_subscription_permission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='permission',
            field=models.ManyToManyField(limit_choices_to={'codename__in': [('advanced', 'Advanced Permission'), ('pro', 'Pro Permission'), ('basic', 'basic permission')], 'content_type__app_label': 'subscriptions'}, to='auth.permission'),
        ),
    ]
